spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Erevna
    username: postgres
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  document:
    chunk:
      size: 1000
      overlap: 200