spring:
  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: llama3.2

      embedding:
        options:
          model: nomic-embed-text
  datasource:
    url: jdbc:postgresql://localhost:5433/erevna
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
document:
  chunk:
    size: 1000
    overlap: 200
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always